version: '3.7'

services:
  wekandb:
    image: mongo:3.2.21
    container_name: wekan-db
    restart: always
    command: mongod --smallfiles --oplogSize 128
    networks:
      - wekan_lan
    volumes:
      - wekan-db:/data/db
      - wekan-db-dump:/dump

  wekan:
    image: quay.io/wekan/wekan:master
    container_name: wekan-app
    restart: always
    depends_on:
      - wekandb
    networks:
      - wekan_lan
    environment:
      - ROOT_URL=https://wekan.museebolo.ch
      - MONGO_URL=mongodb://wekandb:27017/wekan
      - MAIL_URL='smtp://<mail_url>:25/?ignoreTLS=true&tls={rejectUnauthorized:false}'
      - MAIL_FROM='Wekan Notifications <noreply.wekan@mydomain.com>'
      - WITH_API=true
      - BROWSER_POLICY_ENABLED=true
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:wekan.museebolo.ch"
      - "traefik.port=8080"
      - "traefik.frontend.auth.basic=bolo:$$apr1$$Yy8Qdeiq$$qczGFFfSsxIBgiIXjz/R70"
      - "traefik.docker.network=traefik_wan"


volumes:
  wekan-db:
    driver: local
  wekan-db-dump:
    driver: local

networks:
  wekan_lan:
    driver: bridge
  traefik_wan:
    external: true
