version: '3.7'

services:
  wekandb:
    image: mongo:3.2.21
    container_name: wekan-db
    restart: always
    command: mongod --smallfiles --oplogSize 128
    networks:
      - wekan_lan
    volumes:
      - wekan-db:/data/db
      - wekan-db-dump:/dump

  wekan:
    image: quay.io/wekan/wekan:master
    container_name: wekan-app
    restart: always
    depends_on:
      - wekandb
    networks:
#      - traefik_wan
      - wekan_lan
    ports:
      - 80:8080
    environment:
      - ROOT_URL=https://wekan.domain.tld
      - MONGO_URL=mongodb://wekandb:27017/wekan
      - WITH_API=true
      - BROWSER_POLICY_ENABLED=true
#    labels:
#      - "traefik.enable=true"
#      - "traefik.frontend.rule=Host:wekan.domain.tld"
#      - "traefik.port=8080"
#      - "traefik.docker.network=traefik_wan"


volumes:
  wekan-db:
    driver: local
  wekan-db-dump:
    driver: local

networks:
  wekan_lan:
    driver: bridge
#  traefik_wan:
#    external: true
